import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('electronAPI', {
  business: {
    getAll: () => ipcRenderer.invoke('business:getAll'),
    getActive: () => ipcRenderer.invoke('business:getActive'),
    create: (data: unknown) => ipcRenderer.invoke('business:create', data),
    update: (id: number, data: unknown) => ipcRenderer.invoke('business:update', id, data),
    delete: (id: number) => ipcRenderer.invoke('business:delete', id),
    setActive: (id: number) => ipcRenderer.invoke('business:setActive', id),
    saveLogo: (businessId: number, srcPath: string) => ipcRenderer.invoke('business:saveLogo', businessId, srcPath),
  },
  invoice: {
    getAll: (filters?: unknown) => ipcRenderer.invoke('invoice:getAll', filters),
    getById: (id: number) => ipcRenderer.invoke('invoice:getById', id),
    create: (data: unknown) => ipcRenderer.invoke('invoice:create', data),
    update: (id: number, data: unknown) => ipcRenderer.invoke('invoice:update', id, data),
    delete: (id: number) => ipcRenderer.invoke('invoice:delete', id),
    markPaid: (id: number) => ipcRenderer.invoke('invoice:markPaid', id),
    markUnpaid: (id: number) => ipcRenderer.invoke('invoice:markUnpaid', id),
    duplicate: (id: number) => ipcRenderer.invoke('invoice:duplicate', id),
    generatePDF: (id: number) => ipcRenderer.invoke('invoice:generatePDF', id),
    getNextNumber: (businessId: number) => ipcRenderer.invoke('invoice:getNextNumber', businessId),
    exportBackup: (destPath: string) => ipcRenderer.invoke('invoice:exportBackup', destPath),
  },
  finance: {
    getSummary: (year?: number) => ipcRenderer.invoke('finance:getSummary', year),
    getTransactions: (filters?: unknown) => ipcRenderer.invoke('finance:getTransactions', filters),
    addExpense: (data: unknown) => ipcRenderer.invoke('finance:addExpense', data),
    deleteTransaction: (id: number) => ipcRenderer.invoke('finance:deleteTransaction', id),
  },
  settings: {
    get: (key: string) => ipcRenderer.invoke('settings:get', key),
    set: (key: string, value: string) => ipcRenderer.invoke('settings:set', key, value),
    getAll: () => ipcRenderer.invoke('settings:getAll'),
    factoryReset: () => ipcRenderer.invoke('settings:factoryReset'),
  },
  upi: {
    getForBusiness: (businessId: number) => ipcRenderer.invoke('upi:getForBusiness', businessId),
    add: (data: unknown) => ipcRenderer.invoke('upi:add', data),
    update: (id: number, data: unknown) => ipcRenderer.invoke('upi:update', id, data),
    delete: (id: number) => ipcRenderer.invoke('upi:delete', id),
    generateQR: (upiId: string, amount: number, name: string, invoiceNumber: string) =>
      ipcRenderer.invoke('upi:generateQR', upiId, amount, name, invoiceNumber),
    parseUpiId: (upiId: string) => ipcRenderer.invoke('upi:parseUpiId', upiId),
  },
  auth: {
    isSetup: () => ipcRenderer.invoke('auth:isSetup'),
    setup: (password: string, hint: string) => ipcRenderer.invoke('auth:setup', password, hint),
    verify: (password: string) => ipcRenderer.invoke('auth:verify', password),
    changePassword: (oldPassword: string, newPassword: string) => ipcRenderer.invoke('auth:changePassword', oldPassword, newPassword),
    getHint: () => ipcRenderer.invoke('auth:getHint'),
    reset: () => ipcRenderer.invoke('auth:reset'),
  },
  clients: {
    getForBusiness: (businessId: number) => ipcRenderer.invoke('clients:getForBusiness', businessId),
    getById: (id: number) => ipcRenderer.invoke('clients:getById', id),
    save: (data: unknown) => ipcRenderer.invoke('clients:save', data),
    update: (id: number, data: unknown) => ipcRenderer.invoke('clients:update', id, data),
    delete: (id: number) => ipcRenderer.invoke('clients:delete', id),
  },
  shell: {
    openPath: (filePath: string) => ipcRenderer.invoke('shell:openPath', filePath),
    showInFolder: (filePath: string) => ipcRenderer.invoke('shell:showInFolder', filePath),
    readFile: (filePath: string) => ipcRenderer.invoke('shell:readFile', filePath),
    pickFile: (options: unknown) => ipcRenderer.invoke('shell:pickFile', options),
    pickFolder: (title?: string) => ipcRenderer.invoke('shell:pickFolder', title),
  },
  window: {
    minimize: () => ipcRenderer.invoke('window:minimize'),
    maximize: () => ipcRenderer.invoke('window:maximize'),
    close: () => ipcRenderer.invoke('window:close'),
  },
  project: {
    getForClient: (clientId: number) => ipcRenderer.invoke('project:getForClient', clientId),
    getForBusiness: (businessId: number) => ipcRenderer.invoke('project:getForBusiness', businessId),
    create: (data: unknown) => ipcRenderer.invoke('project:create', data),
    update: (id: number, data: unknown) => ipcRenderer.invoke('project:update', id, data),
    delete: (id: number) => ipcRenderer.invoke('project:delete', id),
  },
  document: {
    getAll: (filters?: unknown) => ipcRenderer.invoke('document:getAll', filters),
    getById: (id: number) => ipcRenderer.invoke('document:getById', id),
    generate: (docType: string, clientId: number, projectId: number | null, businessId: number, fieldValues: unknown) =>
      ipcRenderer.invoke('document:generate', docType, clientId, projectId, businessId, fieldValues),
    save: (data: unknown) => ipcRenderer.invoke('document:save', data),
    markSigned: (id: number) => ipcRenderer.invoke('document:markSigned', id),
    generatePDF: (id: number) => ipcRenderer.invoke('document:generatePDF', id),
    delete: (id: number) => ipcRenderer.invoke('document:delete', id),
    hasSignedMSA: (clientId: number) => ipcRenderer.invoke('document:hasSignedMSA', clientId),
  },
});
